### PR TITLE
resized images

### PR DESCRIPTION
**Pull request by HS831**
images were resized.

### CODE REVIEW

**Comment by TeAmP0is0N** [comment]
@HS831 to resolve this conflict just pull our repository so you will get the newly added files and then just commit them in the same PR. I think then it should be resolved.

**Comment by TeAmP0is0N** [comment]
@siddhantchimankar will guide you.

**Review by siddhantchimankar — CHANGES_REQUESTED** [review]
@HS831 git pull karo and according to @vibhubhatia007 ka latest commit, image files ka name and path sahi karo. Toh fir blogs.html ka sara conflict resolve ho jaega. Koi confusion ho toh mujhe pucho.

**Review by vibhubhatia007 — COMMENTED** [review]
https://deploy-preview-21--sdsbitmesra.netlify.app/blogs/generic.html

again the images at this page are not visible although i did add all of them

**Pull request merged**
